### ISSUE TITLE
Ignore teleport event for vehicle exit

### ISSUE THREAD

**Issue by CoolLord22** [CoolLord22/OtherAnimalTeleport#7]
Leaving a vehicle (boat, minecart, and I *think* even rideable mobs) throws a teleport event and could incorrectly send entity failed teleport or  entity left behind messages. Could add a check to just ignore if the teleport cause was a vehicle event.

**Comment by CoolLord22** [comment]
@RhythmicSys Wanted to update you on this, I created a JIRA report for DISMOUNT not being seen as a teleport cause, and they did go ahead and patch it for 1.19.3! See below https://hub.spigotmc.org/jira/browse/SPIGOT-7204. So now, I should be able to ignore DISMOUNT (only on 1.19.3+ unfortunately)

**Comment by RhythmicSys** [comment]
Oh nice :D

**Comment by CoolLord22** [comment]
Pending push from my main PC, issue should be fixed in next patch.
