### ISSUE TITLE
1.19.3 camel support?

### ISSUE THREAD

**Issue by comonier** [CoolLord22/OtherAnimalTeleport#8]
Thank You if it be updated Camel Support !

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/207377849-6a622b8f-88d1-4a0b-ab52-6da3c95fdbbe.png)

**Comment by CoolLord22** [comment]
The plugin works version-independently so it should still work for camels. 
- [ ] Do you have the entity added to the allowed list?
- [ ] Are the entities attached by leads?

**Comment by CoolLord22** [comment]
@comonier Just following up on this issue. Did you get it working?

**Comment by comonier** [comment]
> The plugin works version-independently so it should still work for camels.
> 
> * [ ]  Do you have the entity added to the allowed list?
![image](https://user-images.githubusercontent.com/19571541/209443650-a8acf8f1-047c-489c-adc5-a702418c68d4.png)

> * [ ]  Are the entities attached by leads?
the chat error msg happens when i try mount on any camel
fail_teleport: "&7An entity could not be teleported and is located near (&c%x&7, &c%y&7, &c%z&7)." [config]

camel and all mobs just teleport on same world but i cant see the lead on camels
![image](https://user-images.githubusercontent.com/19571541/209443770-445b65c0-3b99-4bea-9bea-dbd09e20fd65.png)

i guess config not working
#######################
# World groups to prevent cross-flow of entities
world_groups:
- [world, world_nether, world_the_end, hu3, hu3_nether, hu3_the_end]

test worked only on overworld and nether, but i just check your reload command not working so i restarted the server and it works fine.

![image](https://user-images.githubusercontent.com/19571541/209443954-bc74590f-4ca9-47e2-a380-cae39b78c754.png)

maybe that error on chat happens only when we mount on camel

**Comment by comonier** [comment]
confirmed error happens when we mount on camel
![image](https://user-images.githubusercontent.com/19571541/209443991-74474dc2-b96c-4681-b03b-a1e0413b0d9e.png)

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/209444012-de0a7477-2eb7-4755-ae22-782366063570.png)

**Comment by comonier** [comment]
https://youtu.be/Cizwn47-JhA

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/209444514-19dd764f-4601-4c5e-8b10-d44024aa5af8.png)

after updated paper version and worldedit version visual bug was solved - fixed - but...

error on chat of plugin stills

**Comment by comonier** [comment]
visual lead is ok also 
![image](https://user-images.githubusercontent.com/19571541/209444575-85eae2de-18c3-43d4-b920-84b8440faa9f.png)
![image](https://user-images.githubusercontent.com/19571541/209444587-9ad8d0e1-68fc-491a-994a-7e6d5c356de6.png)

**Comment by comonier** [comment]
tested on 1.19.3 paper server on 2 worlds
world [1.19.2] generated
hu3 [1.19.3 generated (with 1.20 datapack)
updated paper and worldedit a lot of bugs was solved
but cant use it on villager yet
and cant cross world [2 overworlds : world and hu3]
but if i cross world to nether to hu3 it works
but not directly world to hu3 overworlds

https://youtu.be/k1EJX2piL2Q [ uploading ]

**Comment by comonier** [comment]
Villager is on file list but still cant capture it with lead.

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/209446874-56fa42f2-c78a-4065-a991-7b7211186558.png)
other bug cant unmount horses donkeys etc

**Comment by comonier** [comment]
only spamming up of fences i guess

**Comment by comonier** [comment]
> Villager is on file list but still cant capture it with lead.

i found other plugin top capture villagers and it works with your plugin like description on spigot

**Comment by CoolLord22** [comment]
The issue with the message spamming on fenced and mounting animals is duplicated by issue #7 and has been patched in the beta releases of the plugin. 

The villager issue, like you said, is fixed by using a third party plugin. OAT does not allow you to lead any entities, just teleport those that can be leashed by default. 

I’d like to help you further with this issue one on one. Do you have Discord or anything similar? Feel free to add me whenever you get some free time. I’d like to hop on the server and take a look myself. 

Thanks! 

(P.S. In the future, try not to spam so many different comments on one issue and instead combine your comments into one big text block. This is because users get individual emails for every reply, so I woke up this morning to 15+ emails haha)

**Comment by comonier** [comment]
> The issue with the message spamming on fenced and mounting animals is duplicated by issue #7 and has been patched in the beta releases of the plugin.
> 
> The villager issue, like you said, is fixed by using a third party plugin. OAT does not allow you to lead any entities, just teleport those that can be leashed by default.
> 
> I’d like to help you further with this issue one on one. Do you have Discord or anything similar? Feel free to add me whenever you get some free time (CoolLord22#7306). I’d like to hop on the server and take a look myself.
> 
> Thanks!
> 
> (P.S. In the future, try not to spam so many different comments on one issue and instead combine your comments into one big text block. This is because users get individual emails for every reply, so I woke up this morning to 15+ emails haha)

ty man, like you said, the bug is only on 1.19.3 spamming error when unmount veicles. ty for everthing.
