### ISSUE TITLE
Up-to-date message

### ISSUE THREAD

**Issue by SimplyJeevS** [CoolLord22/OtherAnimalTeleport#9]
The up to date message is quite useless and a soar on peoples eyes in my opinion.
It would be way better to just let user know whenever there is an update. This would be a simple as adding an if clause to check if you have updated the version number on GitHub or spigot.
If you really wanne keep the up-to-date message around i would suggest putting it in console right after the plugin load!
Apart from that an amazing plugin, hope you will consider it.

**Comment by CoolLord22** [comment]
See above. I think originally that was the plan, to only notify console, but I put it in the wrong if check for when player was null. Thanks for the suggestion! Will be added in 2.2 :)

**Comment by SimplyJeevS** [comment]
No worries glad i could suggest it and thanks for being so on the ball!

**Comment by CoolLord22** [comment]
(Gonna keep this open until it gets merged into main branch)

**Comment by SimplyJeevS** [comment]
Thanks again for getting on-top of this so quickly! Left you a banger of a review on spigot!
